version: "3.1"

services:
  database:
    image: postgres:13.1-alpine
    restart: unless-stopped
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  pgAdmin:
    image: dpage/pgadmin4:4.27
    restart: unless-stopped
    ports:
      - ${PGADMIN_PORT}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - database

  api:
    image: glass-base/api
    restart: unless-stopped
    build:
      context: ./api/
      dockerfile: Dockerfile
    volumes:
      - ./api/:/app
      - /app/node_modules
    ports:
      - ${APP_BACKEND_DEV_PORT}:${APP_BACKEND_DEV_PORT}
    environment:
      PORT: ${APP_BACKEND_DEV_PORT}
      DB_CLIENT: ${DB_CLIENT}
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - database

volumes:
  dbdata:
